import streamlit as st
import pandas as pd
import joblib
import re
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns

# --------------------------------------------------
# Page Config
# --------------------------------------------------
st.set_page_config(
    page_title="AI vs Human Text Classification",
    page_icon="🤖",
    layout="wide"
)

# --------------------------------------------------
# Paths
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# --------------------------------------------------
# Load Data
# --------------------------------------------------
@st.cache_data
def load_data():
    return pd.read_csv(f"{BASE_DIR}/Data/ai and human generated text data.csv")

# --------------------------------------------------
# Load Models
# --------------------------------------------------
@st.cache_resource
def load_models():
    return {
        "Logistic Regression": joblib.load(f"{BASE_DIR}/Models/logistic_regression.pkl"),
        "Naive Bayes": joblib.load(f"{BASE_DIR}/Models/naive_bayes.pkl"),
        "Linear SVM": joblib.load(f"{BASE_DIR}/Models/LinearSVC.pkl")
    }

@st.cache_resource
def load_vectorizer():
    return joblib.load(f"{BASE_DIR}/Models/tfidf_vectorizer.pkl")

df = load_data()
models = load_models()
tfidf = load_vectorizer()

# --------------------------------------------------
# Label Display Map (STRING → DISPLAY)
# --------------------------------------------------
LABEL_DISPLAY = {
    "Human": "🧑 Human-written Text",
    "AI": "🤖 AI-generated Text"
}

# --------------------------------------------------
# Text Cleaning (SAME AS TRAINING)
# --------------------------------------------------
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

# --------------------------------------------------
# Sidebar Navigation
# --------------------------------------------------
st.sidebar.title("Navigation")
menu = st.sidebar.radio(
    "Select Section",
    [
        "🏠 Overview",
        "📊 Exploratory Data Analysis",
        "🤖 Model Performance",
        "🧪 AI vs Human Text Prediction",
        "👨‍💻 About Project"
    ]
)

# ==================================================
# OVERVIEW
# ==================================================
if menu == "🏠 Overview":
    st.title("🤖 AI vs Human Text Classification System")

    st.markdown("""
    **An end-to-end NLP & Machine Learning application that detects whether
    a given text is written by a human or generated by an AI model.**
    """)

    st.markdown("""
    ### Problem Statement
    With the rapid growth of large language models, detecting AI-generated
    content has become critical for education, research, publishing,
    and content moderation.
    """)

    st.markdown("""
    ### Dataset Description
    This dataset was created as part of a **master’s thesis on text classification
    and AI detection**. It is a cleaned and balanced combination of
    **Turing Bench** and **Human vs LLM datasets**.
    """)

    col1, col2, col3 = st.columns(3)
    col1.metric("Total Samples", len(df))
    col2.metric("Human Texts", (df["label"] == "Human").sum())
    col3.metric("AI Texts", (df["label"] == "AI").sum())

    st.success(
        "This project demonstrates a complete NLP workflow — from raw text to deployed ML predictions."
    )

# ==================================================
# EDA
# ==================================================
elif menu == "📊 Exploratory Data Analysis":
    st.title("📊 Exploratory Data Analysis")

    st.subheader("Class Distribution")
    st.bar_chart(df["label"].value_counts())

    st.divider()

    st.subheader("Text Length Distribution")
    df["text_length"] = df["text"].apply(lambda x: len(x.split()))

    fig, ax = plt.subplots(figsize=(8, 4))
    sns.boxplot(
        x="label",
        y="text_length",
        data=df,
        ax=ax
    )
    ax.set_xlabel("Text Type")
    ax.set_ylabel("Number of Words")
    st.pyplot(fig)

    st.success(
        "Human and AI texts show noticeable stylistic and structural differences."
    )

# ==================================================
# MODEL PERFORMANCE
# ==================================================
elif menu == "🤖 Model Performance":
    st.title("🤖 Model Evaluation & Comparison")

    st.markdown("""
    Models were trained using **TF-IDF vectorization** and evaluated on a
    held-out test set.
    """)

    results = pd.DataFrame({
        "Model": ["Logistic Regression", "Naive Bayes", "Linear SVM"],
        "Accuracy (%)": [75, 74, 77]
    })

    st.table(results)

    st.markdown("""
    **Insight:**  
    Linear SVM performs best by learning strong decision boundaries
    over TF-IDF features.
    """)

# ==================================================
# PREDICTION
# ==================================================
elif menu == "🧪 AI vs Human Text Prediction":
    st.title("🧪 AI vs Human Text Detection")

    selected_model_name = st.selectbox(
        "Select Machine Learning Model",
        list(models.keys())
    )

    model = models[selected_model_name]

    user_text = st.text_area(
        "Paste text to analyze",
        height=220,
        placeholder="Enter text here..."
    )

    if st.button("Predict"):
        if user_text.strip() == "":
            st.warning("Please enter some text.")
        else:
            cleaned = clean_text(user_text)
            vectorized = tfidf.transform([cleaned])
            prediction = model.predict(vectorized)[0]   # 'Human' or 'AI'

            st.success(LABEL_DISPLAY[prediction])

# ==================================================
# ABOUT
# ==================================================
elif menu == "👨‍💻 About Project":
    st.title("👨‍💻 About the Project")

    st.markdown("""
    ### 🤖 AI vs Human Text Classification

    This project focuses on detecting AI-generated text using
    **classical NLP techniques and machine learning models**.
    """)

    st.markdown("""
    **Key Highlights**
    - Text preprocessing & TF-IDF vectorization
    - Multiple ML model comparison
    - CPU-friendly, deployment-ready design
    - Real-time inference using Streamlit
    """)

    st.markdown("""
    **Tech Stack**
    - Python  
    - NLP (TF-IDF)  
    - Scikit-learn  
    - Pandas, NumPy  
    - Streamlit  
    """)

    col1, col2 = st.columns(2)
    with col1:
        st.link_button("💼 LinkedIn", "https://www.linkedin.com/in/kornu-sai-govinda-rao-b077a9286/")
    with col2:
        st.link_button("📂 GitHub", "https://github.com/sai-govinda-rao")
